name: Test and Update Coverage

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

permissions:
  contents: write

jobs:
  test-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests with coverage
        run: npm run test:coverage

      - name: Update README coverage section
        run: npm run coverage:update-readme

      - name: Commit changes (if any)
        if: ${{ github.event_name == 'push' }}
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add README.md badges/coverage.json
            git commit -m "ci: update README coverage [skip ci]"
            git push
          else
            echo "No README changes to commit."
          fi
